# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WGH+s/Ezt4bEBfnN3J8942vIDWqruFPU2Y1Tpfj22CN2uky4mp974y9/ZvfX++6IljDSCMVU1ZcSMId/+Qsd7+XU7W0clM8WhYgGzZI4FaNigsLvFGokZBAQONo5tLM8b0xWrqL6YMcVSJOVZNMb32HRxZlGthaTTxhAlRsBymLdbtzYLAsai8/+WBWt7I3Po4w+YnjuN4dG1t8WRyEKEPX1TKpOMLDqdGjUi0VzG8yyEwQBmgn2KihHYW0/gm8VE48hCmQwucoraqizem12LJn4Vz5z4iee+3gTklPFWfoO0A+xcHd8lmvuAy3vS6HK7K2qOIQBpIs/2/uwk4KCGeyJE5E8QsMmIES8AXIROQov5GBRp5c21xVQNQZeMT90Oy9s4h71grvAMcciPBxaSvCnvyVxIvXOE3ujSYIHjBEsqriWu0eThE7n98Q1CB1Drb9FtcLXtJC7ioMFBEE3vsUeU2+P4W7SrcCYHRdtg4EPEtWZvN0zIgzY7UY33bRH/DBp6bSdUbqNe1oSNkxHFcE8jIQPs2ykdC5ur9CzKx93jkXQp8pMEierXswil6ybgy/+WHRBffHPQGqkUsCmiqSAfDKBFGCfmxzk70RXnkIRkeQJ5jgzfu5DQ/05RcRGkhaQv/99eoH0aAhOez7jBLhftV6/Mo7hxvK0P7dMVsQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
