travis:
  secure:
    BINSTAR_TOKEN: gHlIAB5RgZDSsphUJQMHENivWcH41CXk8WHhM3GLROH6+yZqvRMsej+BqaQNIBcJ8RrjdZ3o3GXLb3hOTABAVYaIDM++1h+6Hoz3QyjLfbHHa4ETo5V3QBBzqschtchxLveofBdXLGfR6iQZ9wziuUfi693Vy66liXMuc4fcJtY6f0zdrCiEqO/wUkQwkJJguqlghgPTdTW+jIeXN3PvLpA3ifsHqtj/oxPEBRm/6Gqm5FgKMDsiAFYLGqvNKlwhylNNJnYcvwyzsADN7INQdq3+/WGwQQq7N5YkklZGh9eZ/z0KJp4bbBABfKkx8m8Ekjds/VTUduoZYlbyd2MGFCvyVQw4jQlR2rqbjTmC5SgV3973cWs3cUf/DMuEMdfrnHpOOF7Mw44hia0+F6CLJDTbtwSaAFR9qY8XmVbi9h1QbJsxjtFPOXWI1Za5fMRiuvcZzJIPCsqyKGcqgPRy2NJA882PQ+ekRd2XF521U+aLw6ZfbhmTtouSpHVYL+Eac7/jCZWmMw6LDBllCNDOQd/yYnAUsOH90kvD2iuXt6lyqxoBNoJsS2OthY4kn5BZLaZ9ghimuG02etRwNNL9Vn6jBmd8Ppd9ANC9OQbB27HHiIrBAsg/HKqtAB1I45eshStllRXCfGaEtw0ETv91QEQuKoX1ioBDoxIVPX5DzXU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
