travis:
  secure:
    BINSTAR_TOKEN: OznV05DwPW6lUvAy6PjJvMO+es1oI+Y11D0dEYPtGZAgpAVkOziwOgFgAluUmboW5DGxWZAH9MvXq7RQ6kYHnqQYfX8iV2xr0wDQsrV1diEOBTNMsUQhPk4F9EpWca+vqmhMQQDx1tBCeN7mHc5XpHszfloznjj8oBoq7/yDhFRWvHChiVW3zpnwrbzSagwqtglLcwKMQ2vDMg0jbaXIdnzMsJH6vrIIBRlngM3p3w4Mtby1kOx7ZrjgvAdRzYNifd374gkQ6jIsM4zfNHc7j7+quP0t7ymnssdCw/E0eo4dulWGzglNVh9makcXmkAwSKGD0kF5ZGGQQsQtaw4Cr/nk6434FYyTDbSm+DQzIlfze3Wl/5XzgJpNMx5hZgBB7+A1/okdTkVZ/11Pt+v6e9cjUwmD6XBTk+p8asRCaJ2hTqax9n0m470a9C4Ab1U4JvpqBTCTL2WvdbRsukTwdlInlOMQcKL3kRYQ+tMHAsoevtuZVj/Z24D3Rj2GHYIcWIC+7aUpoNfpyJVbdJGioYBYdfEGW6qKE0sTglNqPdBWZBKDosfZN1459HzGnc0TXw3K0Lt5NRx/bbIkm+9nFRZaH00kxqq8fUCCI2dgirqde0W8VPvWCY4tL8nuHXb+BftvToAnMvugWtAGPBYjACFnMqzVyO+hjv6ls1cQuFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
