travis:
  secure:
    BINSTAR_TOKEN: fUX+wTK/CrkJbnD6DnkkxWD6pAOESHbmlDLNfnoWnbgfUWPNu0KclsVAzNpSe7hS1o2APr0g9MQBW1giiVwIcmAWXzwQlF/NCm/yxFkK5Y3VgOFdDjvPE2OQGOCpXmhJGWLiboYUAgjF937C3fA7lHFc9XuYSvmkmM+FrNTyCov1IkzqUwNB+lvj70fHz7+dqFvnjakCb2wzBZJaUcvNQrEyAdp/kfKjQ6BDolZGMgWyLenelQEQn/GaOkJIwBDW8DSJUmkCXAd8WApRTs1SURQnzBvS7iasp4QAgcfrAafW6K1FvP2WBrtuh0tnLCrsbMYRaHNABJw5XB0XFdeFGt6ofs6sf0FvpSoTGWOueNU/Xc3tAkCbQkySeeeaYHC2jTYpo5kUV5dv7NPTEs1eYcYvXucE58zcSLYWI9Ipk0lesh6O/1gbCvT2JHrwien1iBbcX/FxixL3xc0IEIYwa8iaPOHGA4L7j4yyPpB+LgdVK8qEF4AbLPW1YjdOiSfFGkC+Jm1z3bb3la0wwHUIpeOYtr/fiHTC/cCM70t+xa3VJLgUBlMR+qPTYBxL+qc0u3iDG+IYVvT7krMWJTntz2ifm3wXIGSeBAH5pG3UzVNYe0VjJX29JhogNiZGyrNVnIzBwiIeGxhMPj49umCl4iPRyoJ1JoExLBOEQZn1ha0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
