travis:
  secure:
    BINSTAR_TOKEN: g62XJt/qieGb0IhnShC/jeNLCkpfmTzZyQYRqZWnGVxTy7sM7sshBisDrFpEVklUdwfZPmo5S7vHffb2lF5FB3FqDmN/G9cg5WrQMl+tbb0B9vVnDzf68HKoL4uRWsWbKA8WTtgb4c744v6BzLDzXBCVh7xvpyoEWwyyUiiq7Jk1jfyDl9TUUW+QtPoSxe6oF96a30AiaUWl3nOuXVQxnDPotvlxlf4ug2HulA63Mk0I2Dj+j94oyc+n58unWxBm+t4qEpOenMxD108FHgS18q9G4W22SMmNuxkL9uiCxszlm4ffVGFtQ5TJkY8NUEyqGGN30PXiy09ukwv6QCgmljUCfRPUvZ1tz79qFqPMzd9+e65+FXuqLo99T1Y/3/5LRBph/Q/xIypdZjA5qrzpDop33pCNT4MAOKnE50uIQaGGxzPq0A73C55tffoogTRCNh5PpmGYVCVA5dBP2n+x8VwEea3Z2f/fhpX9cEvNJdz2mEetwYwNFclWwEpdYdaWcG+tdunPXQJELY/5le+WOXCqEG2ICqnVXM/sV9MyJPHfEhfWKhDVCUkAPLRghFD9/c1GWWknlPZzdnnlGC+wWAx9YfJVyYYo5jGOc3AMPkS2xm7uKYXr2V3N/V3m+CX7iY7/ZxJGC2n8CspR53VSHJoT4uevz98C219NPAkUSZA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
