travis:
  secure:
    BINSTAR_TOKEN: WGH+s/Ezt4bEBfnN3J8942vIDWqruFPU2Y1Tpfj22CN2uky4mp974y9/ZvfX++6IljDSCMVU1ZcSMId/+Qsd7+XU7W0clM8WhYgGzZI4FaNigsLvFGokZBAQONo5tLM8b0xWrqL6YMcVSJOVZNMb32HRxZlGthaTTxhAlRsBymLdbtzYLAsai8/+WBWt7I3Po4w+YnjuN4dG1t8WRyEKEPX1TKpOMLDqdGjUi0VzG8yyEwQBmgn2KihHYW0/gm8VE48hCmQwucoraqizem12LJn4Vz5z4iee+3gTklPFWfoO0A+xcHd8lmvuAy3vS6HK7K2qOIQBpIs/2/uwk4KCGeyJE5E8QsMmIES8AXIROQov5GBRp5c21xVQNQZeMT90Oy9s4h71grvAMcciPBxaSvCnvyVxIvXOE3ujSYIHjBEsqriWu0eThE7n98Q1CB1Drb9FtcLXtJC7ioMFBEE3vsUeU2+P4W7SrcCYHRdtg4EPEtWZvN0zIgzY7UY33bRH/DBp6bSdUbqNe1oSNkxHFcE8jIQPs2ykdC5ur9CzKx93jkXQp8pMEierXswil6ybgy/+WHRBffHPQGqkUsCmiqSAfDKBFGCfmxzk70RXnkIRkeQJ5jgzfu5DQ/05RcRGkhaQv/99eoH0aAhOez7jBLhftV6/Mo7hxvK0P7dMVsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
